services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - "./gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped
    networks:
      - infrastructure
      - ext_network
    depends_on:
      - client
      - server

  client:
    build:
      context: ./trapWord-client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3120
    volumes:
      - './trapWord-client/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    networks:
      - infrastructure

  server:
    build:
      context: ./trapWord-server
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - 8000
    networks:
      - infrastructure

  redis:
    image: "redis/redis-stack:edge"
    restart: unless-stopped
    ports:
      - 6379
    networks:
      - infrastructure

networks:
  ext_network:
    driver: bridge
    external: true
  infrastructure:
    internal: true
