on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
  build_docker:
      name: build docker
      runs-on: ubuntu-latest
      steps:
        - name: pull
          run: "sudo docker compose -f docker-compose.prod.yml -p w2bprod up -d --build"
  clean:
      name: clean up
      runs-on: ubuntu-latest
      steps:
        - name: clear up and die
          run: rm -rf ~/.ssh
      
